// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFG0x9_2sq5Z4bUFRfqUdTDVd6GJSSP8E',
    appId: '1:982596040495:web:8bbf3c5618466ba7cd53da',
    messagingSenderId: '982596040495',
    projectId: 'synctalk-36875',
    authDomain: 'synctalk-36875.firebaseapp.com',
    storageBucket: 'synctalk-36875.firebasestorage.app',
    measurementId: 'G-X2V0VP2PHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOskzwBEU-eoz2Y80Vu0Ff6H_i98brSIg',
    appId: '1:982596040495:android:9dc553f91ba8d12bcd53da',
    messagingSenderId: '982596040495',
    projectId: 'synctalk-36875',
    storageBucket: 'synctalk-36875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfobeCXBJOtyW32cFTqPJ1eA8Ad4R1CAk',
    appId: '1:982596040495:ios:f039f37115e6ba54cd53da',
    messagingSenderId: '982596040495',
    projectId: 'synctalk-36875',
    storageBucket: 'synctalk-36875.firebasestorage.app',
    androidClientId: '982596040495-b9r4in0bhd4pdn8jtj5c8av0tcs23bfh.apps.googleusercontent.com',
    iosClientId: '982596040495-3lttf96ha5iamrh6tlu5r6f0aaugjjje.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncTalkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfobeCXBJOtyW32cFTqPJ1eA8Ad4R1CAk',
    appId: '1:982596040495:ios:f039f37115e6ba54cd53da',
    messagingSenderId: '982596040495',
    projectId: 'synctalk-36875',
    storageBucket: 'synctalk-36875.firebasestorage.app',
    androidClientId: '982596040495-b9r4in0bhd4pdn8jtj5c8av0tcs23bfh.apps.googleusercontent.com',
    iosClientId: '982596040495-3lttf96ha5iamrh6tlu5r6f0aaugjjje.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncTalkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFG0x9_2sq5Z4bUFRfqUdTDVd6GJSSP8E',
    appId: '1:982596040495:web:4fc99055bbf8f622cd53da',
    messagingSenderId: '982596040495',
    projectId: 'synctalk-36875',
    authDomain: 'synctalk-36875.firebaseapp.com',
    storageBucket: 'synctalk-36875.firebasestorage.app',
    measurementId: 'G-ZZJJZ2EZ0H',
  );
}
